Wrong GPO
ukncsc/lme pull request #3
Opened 2019-04-24 09:41 UTC by super0xbad1dea

LME-Sysmon-Task is not part of LME-WCE-*. Please correct the link to LME-Sysmon-Task (https://github.com/ukncsc/lme/tree/master/Chapter%202%20Files/GPO%20Deployment)

2019-04-26 09:46 UTC, duncan-ncc commented
Thanks for your time, This is obviously is an issue. I would propose that the link was relative rather than fully qualified to ensure compatibility with forks and branches.

2019-04-26 13:39 UTC, duncan-ncc requested changes
As discussed in the comments, I propose you changing the URL to relative.

2019-04-26 13:46 UTC, super0xbad1dea commented
I propose that, instead of URL you zip the GPO folder like you did with the GPO-files for the logging configuration on client and server. Makes it more comfortable to download a zipped file.

2019-04-26 13:47 UTC, super0xbad1dea reviewed
relative path

2019-04-26 13:47 UTC, super0xbad1dea commented on docs/chapter2.md
> +Import the [LME-Sysmon-Task](https://github.com/ukncsc/lme/tree/master/Chapter%202%20Files/GPO%20Deployment) GPO into group policy management and link the object to a test Organisational Unit (OU). O
```suggestion
Import the [LME-Sysmon-Task](/Chapter%202%20Files/GPO%20Deployment) GPO into group policy management and link the object to a test Organisational Unit (OU). Once the GPO is confirmed as working in your environment then you can link the GPO to a larger OU to deploy LME further.
```

2019-04-26 13:55 UTC, duncan-ncc commented on docs/chapter2.md
> +Import the [LME-Sysmon-Task](https://github.com/ukncsc/lme/tree/master/Chapter%202%20Files/GPO%20Deployment) GPO into group policy management and link the object to a test Organisational Unit (OU). O
Looks good.

2019-04-26 13:55 UTC, duncan-ncc approved these changes

2019-04-29 09:18 UTC, duncan-ncc commented
I am going to close this PR as the URL in question has been changed as part of https://github.com/ukncsc/lme/commit/7168abd380e92d4c557425f15a4c021b56556f14.
Thanks for your contribution.

2019-04-29 09:18 UTC, closed without merging