Amending log retention period
ukncsc/lme pull request #66
Opened 2020-05-21 22:33 UTC by lllama

2020-05-28 10:32 UTC, duncan-ncc requested changes

2020-05-28 10:32 UTC, duncan-ncc commented on docs/retention.md
> +disk space available. If disk space is exhausted then the solution will
Worthwhile mentioning that this must be below 85% of total disk due to disk watermarking [Link to Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html)

2020-05-28 10:32 UTC, duncan-ncc commented on docs/retention.md
> +space.
Worth mentioning must be below 85% [Elasticsearch disk watermarking](https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html)

2020-05-28 14:50 UTC, duncan-ncc approved these changes

2020-05-29 08:28 UTC, a-d-a-m-b approved these changes

2020-06-01 08:37 UTC, merged